using System.Collections.Generic;

namespace DeviValidate.Core.Reporting;

/// <summary>
/// Procedure for comparing a new hash with a hash another tool already recorded.
/// The Windows app shows <see cref="P:DeviValidate.Core.Reporting.VerificationGuide.Sections" />. The verification record prints <see cref="F:DeviValidate.Core.Reporting.VerificationGuide.RecordSummary" />.
/// </summary>
public static class VerificationGuide
{
	public const string Banner = "To verify, compare a new hash of the file with a hash another tool already wrote down. Get that hash from the physical analyzer, the forensic report, an FTK Imager log, a sum file, or a CSV. You do not re-image the drive in this program, and this program does not connect to the analyzer.";

	public const string RecordSummary = "A verification needs two things: the file or folder, and a hash that another tool already wrote down. DEVI Validate reads the file and computes a new hash. It then compares that new hash with the earlier one. It does not image a drive. It does not connect to a physical analyzer, a forensic suite, or FTK Imager. If that other tool already printed a hash, bring the hash here. You do not run the acquisition again inside this program.\n\nGet the earlier hash from the report you already have. That may be the hash list or acquisition report from a physical analyzer or other forensic tool, an FTK Imager text log, a sum file, a CSV or TSV, a DEVI Validate JSON record, or one hash copied from a report and pasted for a single file. Use the same algorithm the first tool used. SHA-256, SHA-1, and MD5 are different, and a SHA-256 result will not match an MD5 result for the same file. For an FTK Imager log, the checksum is the hash of the acquired data. Compare it with the single raw image, not with an E01 or L01 container. This version does not read a hash stored inside an E01 file.\n\nPress Verify only after both the evidence and the earlier hash are in place. Hash only computes a new hash and does not compare it with anything, so Hash only is not a verification. Match means the new hash is the same as the hash written down before. The file we read is the same file that hash describes. Mismatch, shown in red, means the two hashes are not the same. A red result can mean the file changed, that this is a different file, that the hash was copied wrong, that the algorithm does not match, or that the tools were pointed at different copies, including hashing a container when the first hash was of the raw data. A red result does not show who changed the file, when it changed, or why. It does not show that someone tampered with the file or deleted it.\n\nA prosecutor, a defense attorney, or another examiner can repeat the check without this program. On Windows, use certutil -hashfile with SHA256, or Get-FileHash -Algorithm SHA256. On many other systems, use sha256sum. Use SHA1 or MD5 when that is the algorithm on the first report. Compare the hex values. This check verifies the bytes only. It does not show who made the file, what the file means, or whether a chain of custody is complete. It does not certify the tool, the laboratory, or the case.";

	public static IReadOnlyList<ReportSection> Sections { get; } = System.Array.AsReadOnly(new ReportSection[14]
	{
		new ReportSection("1. What you are checking", "This program reads a file or a folder you already have and computes a new hash. If you also give it a hash that was written down earlier, it compares the two.\n\nThat comparison is the verification. The earlier hash has to come from somewhere else. This program does not create the original acquisition. It checks the bytes you point it at against a value someone already recorded.\n\nThis record independently recomputes hash values and compares them with values recorded by another tool or process.\n\nThe check is offline. Evidence is opened read-only. Nothing is uploaded, and nothing is sent to a cloud service."),
		new ReportSection("2. Where the comparison hash comes from", "You do not re-image the drive in this program. You do not have to run the physical analyzer again if its report already contains the hash. You copy or export that hash, and you bring it here.\n\nYou still need the file. A hash on a report is not enough by itself. Step 2 is the file or folder. Step 3 is the earlier hash. Verify reads the file, computes a new hash, and compares.\n\nIf you do not have an earlier hash, this program cannot look one up. Hash only will compute a new hash and stop. That new hash is not a verification, because there is nothing to compare it with. Go back to the report from the tool that acquired or processed the evidence, and get the hash from there."),
		new ReportSection("3. Physical analyzer or other forensic tool", "A physical analyzer, a forensic suite, or an acquisition tool often hashes the evidence when the device is acquired or when a report is created. DEVI Validate does not connect to that analyzer. It does not log into it, read its case database, or send the file back to it. The analyzer does not need to be open while you verify.\n\nOpen the analyzer's report, acquisition log, or hash export. Find the hash it recorded for the image or the file. It is a long string of the letters a through f and digits. Note the algorithm name beside it: SHA-256, SHA-1, or MD5.\n\nIf that tool can export a sum file or a CSV of paths and hashes, export it and drop that file in step 3. A sum file looks like the output of sha256sum. A CSV has a path column and a hash column.\n\nIf the hash is only on the screen or in a PDF, copy it and paste it into the hash box in step 3. Pasting is safer than typing. One wrong character produces a mismatch. Paste only when step 2 is a single file. Do not paste a hash and also choose an expected file. Use one or the other.\n\nThis version does not open a Cellebrite UFDR, a Magnet AXIOM case, or a hash stored inside an E01 file. If the hash lives only inside one of those, copy it out or export a sum file or CSV, then use that export here.\n\nUse the same object the first hash describes. If the analyzer hashed a raw image, often a file ending in .dd, .img, .bin, or .raw, step 2 must be that raw image. If it hashed one logical file, step 2 must be that file. If it hashed a folder of files and you have a list of those hashes, step 2 must be that folder. Hashing a zip of the files, a different copy, or an E01 container when the first hash was of the raw data will not match, even when the case is the same."),
		new ReportSection("4. FTK Imager text log", "If the first hash is in an FTK Imager text log, drop that log in step 3. The lines that matter look like MD5 checksum, SHA1 checksum, or SHA256 checksum, followed by the hex value. This program uses the hex value. It ignores the word after the hash, such as verified, and it hashes the file again itself.\n\nThat checksum is the hash of the acquired data. Compare it with the single raw image of that data. Do not choose the E01 or L01 container. This version does not read a hash stored inside an E01 file. If you need the hash of the container file itself, supply a hash of that container, not the acquired-data checksum from the log.\n\nThe log is one checksum, not a list of files inside the image. Step 2 must be one file, the raw image. A folder will be refused. A log that lists more than one image segment will be refused. This version does not treat a split set as one file."),
		new ReportSection("5. Sum file, CSV, JSON, or a pasted hash", "A sum file is a text list of hashes and paths, including GNU md5sum, sha1sum, and sha256sum output, and the BSD form. Drop it in step 3 and put the matching files in step 2.\n\nA CSV or TSV is a spreadsheet export with a path column and a hash column. Drop it in step 3.\n\nA DEVI Validate JSON record from an earlier run can be an expected source. The record hash must match or the file is refused.\n\nA pasted hash is for one evidence file. Leave the expected-file choice empty when you paste.\n\nPaths are compared after slash direction is normalized. A path that contains .. is rejected. When the expected entry is only a file name, or an absolute path from another machine, a unique file name can match. Two files with the same name in different folders are not paired by name alone."),
		new ReportSection("6. Steps in this window", "Step 1. Fill in Case details. Examiner and case number are required before Verify or Hash only will run. The examiner name and agency fill in from Settings. The validation date is today unless you change it. Validated by and Lab procedure are optional; Lab procedure can name the tool the expected hash came from. These fields are written on the record. They do not change the hash. A blank optional field prints Not recorded.\n\nStep 2. Drop the evidence file or folder, or use Choose file or Choose folder. This must be the same bytes the earlier hash describes.\n\nStep 3. Drop the log, sum file, CSV, or JSON, or paste one hash. Set Algorithm, beside the step title, to the algorithm on the first report when you paste a hash. SHA-256 is the default. A list or log sets the algorithm for you. This step is required for a comparison. You can leave it empty only when you are not verifying.\n\nStep 4. Press Verify. Wait until the progress line finishes. It shows the file count, the bytes read, and the current path. Use Cancel if you chose the wrong file. Do not verify a file that is still being copied.\n\nRead the banner, the counts, and the table. Export PDF, HTML, JSON, or a validation package from Exports and tools at the bottom of the window. Reports are written outside the evidence folder. The program refuses to save a report inside the evidence location."),
		new ReportSection("7. Hash only is not a verification", "Hash only computes a new hash of step 2 and does not look at step 3. Use it when you need a hash to write down and no earlier hash exists yet. The banner will say the hash is complete. That is not a match and it is not a mismatch. Nothing was compared.\n\nTo verify later, keep that hash with the file and compare it on a later run, or bring an expected hash from the other tool and press Verify."),
		new ReportSection("8. Use the same algorithm", "MD5, SHA-1, and SHA-256 are not interchangeable. The same file produces a different hash under each one.\n\nMD5 is 32 hex characters. SHA-1 is 40. SHA-256 is 64. If the length does not match the algorithm you selected, you have the wrong algorithm or a damaged copy of the hash.\n\nUpper and lower case do not matter. A space in the middle of the hash does matter. A hash that was wrapped across two lines in a PDF must be joined into one line before you paste it, with no space added where the line broke."),
		new ReportSection("9. What a match means", "A match means the new hash is the same as the hash written down before. The file we read is the same file that hash describes. Anyone can check the file again with sha256sum, certutil -hashfile, or Get-FileHash. This check verifies the bytes only. It does not show who made the file, what the file means, or whether a chain of custody is complete.\n\nA match does not prove who created the file, that the first examiner followed a procedure, or that the file is relevant or admissible. It does not prove the physical analyzer was configured correctly. It proves that the bytes read now are the same bytes that earlier hash describes."),
		new ReportSection("10. What a red mismatch means", "Red means the new hash is not the same as the hash written down before. The file we read is not the same as the file that hash describes. The notes below say what that can and cannot mean.\n\nA red result can mean a few ordinary things. The file may have changed after the first hash was made. This may be a different file, or a different copy. The expected hash may have been copied wrong, or taken from another file. The algorithm may not match, for example an MD5 value compared using SHA-256. The tools may have been pointed at different objects. A common case is hashing an E01 container when the first hash was of the raw acquired data, or hashing a folder when the first hash was of one image file.\n\nA red result does not show who changed the file, when it changed, or why. It does not show that someone tampered with the file or deleted it. It does not by itself show that evidence was planted or that a report is false. It only shows that the two hashes are not the same. Rule out the ordinary causes before anyone treats the result as proof of tampering."),
		new ReportSection("11. Missing and Extra", "Missing. A path was on the expected list, but that file was not among the files we read. Its hash was not checked. Missing is not shown in red. It can mean the file is not in the folder you chose, or the path in the list does not match a file in that folder.\n\nExtra. We read a file that was not on the expected list. Its new hash is in the table, and there was no earlier hash to compare. Extra is not shown in red. Extra does not mean the file is suspicious. It means this check did not have a prior hash for it."),
		new ReportSection("12. How counsel or another examiner can check again", "You do not have to trust this program's screen. The hash is a standard value. A prosecutor, a defense attorney, or another examiner can compute it with a tool already on their computer and compare the characters.\n\nWindows Command Prompt: certutil -hashfile \"C:\\Evidence\\image.dd\" SHA256\n\nWindows PowerShell: Get-FileHash -Algorithm SHA256 -Path \"C:\\Evidence\\image.dd\"\n\nMany Linux and macOS systems: sha256sum image.dd\n\nWhen the first report used SHA-1, use SHA1 with certutil and Get-FileHash, and sha1sum on the other systems. When it used MD5, use MD5 and md5sum.\n\nCompare three values when you have them: the hash in the original report from the physical analyzer, the FTK log, or the sum file; the hash in this record; and the hash from certutil, Get-FileHash, or sha256sum. Letter case does not matter. If they are the same, the bytes match. If they differ, the bytes do not match.\n\nCounsel can do this on a copy of the file without using DEVI Validate at all. The original report's hash is the comparison value. This program is one way to recompute. It is not the only way.\n\nTo check a saved DEVI Validate JSON record, run devi-validate check on that JSON file, or recompute the SHA-256 of its canonical JSON with the integrity hash set to an empty string. That record hash covers the JSON. It does not cover the PDF or HTML bytes."),
		new ReportSection("13. What this check cannot prove", "It does not show who created, copied, or changed a file.\n\nIt does not show when a change happened, or why two hashes differ.\n\nIt does not show that someone tampered with evidence or deleted a file.\n\nIt does not review the words or pictures inside a file.\n\nIt does not complete a chain of custody, and it does not check whether metadata is accurate.\n\nIt does not certify the laboratory, the method, or the case. It is not a statement of court acceptance, NIST approval, or CJIS compliance.\n\nA passing self-test means this copy of the program reproduced published test vectors and a small read-only check on this machine. Run it from Tools when your procedure asks for a tool check. A passing self-test does not certify the program for casework."),
		new ReportSection("14. Before a result is used in a case", "Confirm the algorithm on this window matches the first report.\n\nConfirm step 2 is the same object that first hash describes. That is the raw image rather than the container, or this folder rather than another copy.\n\nConfirm the expected hash was copied from the original report. Keep that report with this record so a reader can see both hashes.\n\nRead a red row as two hashes that differ, until the ordinary causes in section 10 are ruled out. Do not describe a mismatch as proof of who changed a file.\n\nEach lab or agency should validate this tool under its own procedure before relying on it. The validation fields on the record are what was typed at the time. An empty field prints Not recorded.")
	});

}
